CREATE TABLE IF NOT EXISTS symbol (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    symbol_code VARCHAR(64) NOT NULL UNIQUE,
    symbol_name VARCHAR(255),
    market VARCHAR(32) NOT NULL,
    asset_type VARCHAR(32),
    currency VARCHAR(16),
    enabled TINYINT DEFAULT 1,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS watchlist (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    symbol_code VARCHAR(64) NOT NULL,
    group_name VARCHAR(64) DEFAULT 'DEFAULT',
    priority INT DEFAULT 0,
    note VARCHAR(1000),
    enabled TINYINT DEFAULT 1,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE(symbol_code, group_name)
);

CREATE TABLE IF NOT EXISTS daily_kline (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    symbol_code VARCHAR(64) NOT NULL,
    trade_date DATE NOT NULL,
    open_price DECIMAL(20, 6) NOT NULL,
    high_price DECIMAL(20, 6) NOT NULL,
    low_price DECIMAL(20, 6) NOT NULL,
    close_price DECIMAL(20, 6) NOT NULL,
    volume DECIMAL(24, 4),
    amount DECIMAL(28, 4),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE(symbol_code, trade_date)
);

CREATE TABLE IF NOT EXISTS indicator_snapshot (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    symbol_code VARCHAR(64) NOT NULL,
    trade_date DATE NOT NULL,
    ma5 DECIMAL(20, 6),
    ma10 DECIMAL(20, 6),
    ma20 DECIMAL(20, 6),
    ma60 DECIMAL(20, 6),
    rsi14 DECIMAL(10, 4),
    atr14 DECIMAL(20, 6),
    volume_ma20 DECIMAL(24, 4),
    volume_ratio DECIMAL(12, 4),
    five_day_return DECIMAL(12, 4),
    distance_to_ma20 DECIMAL(12, 4),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE(symbol_code, trade_date)
);

CREATE TABLE IF NOT EXISTS technical_signal (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    symbol_code VARCHAR(64) NOT NULL,
    trade_date DATE NOT NULL,
    signal_type VARCHAR(32) NOT NULL,
    signal_level VARCHAR(32),
    trend_state VARCHAR(32),
    technical_score INT,
    entry_reference DECIMAL(20, 6),
    stop_loss_reference DECIMAL(20, 6),
    take_profit_reference DECIMAL(20, 6),
    reason TEXT,
    risk_note TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE(symbol_code, trade_date, signal_type)
);

CREATE TABLE IF NOT EXISTS ai_analysis_snapshot (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    symbol_code VARCHAR(64) NOT NULL,
    analysis_date DATE NOT NULL,
    asset_name VARCHAR(255),
    market VARCHAR(32),
    asset_type VARCHAR(32),
    sentiment_score INT,
    risk_score INT,
    risk_level VARCHAR(32),
    market_state VARCHAR(32),
    action_constraint VARCHAR(64),
    summary TEXT,
    positive_factors TEXT,
    negative_factors TEXT,
    risk_factors TEXT,
    contrarian_view TEXT,
    raw_report LONGTEXT,
    source_system VARCHAR(128) DEFAULT 'daily_stock_analysis',
    call_status VARCHAR(32) DEFAULT 'SUCCESS',
    error_message TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_ai_analysis_symbol_date (symbol_code, analysis_date),
    INDEX idx_ai_analysis_symbol_date (symbol_code, analysis_date),
    INDEX idx_ai_risk_level (risk_level),
    INDEX idx_ai_call_status (call_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS final_trade_decision (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    symbol_code VARCHAR(64) NOT NULL,
    decision_date DATE NOT NULL,
    technical_signal VARCHAR(64),
    technical_score INT,
    ai_sentiment_score INT,
    ai_risk_score INT,
    ai_risk_level VARCHAR(32),
    final_action VARCHAR(64),
    position_policy VARCHAR(64),
    decision_reason TEXT,
    reject_reason TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_final_decision_symbol_date (symbol_code, decision_date),
    INDEX idx_final_decision_symbol_date (symbol_code, decision_date),
    INDEX idx_final_action (final_action),
    INDEX idx_ai_risk_level (ai_risk_level)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS trade_journal (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    symbol_code VARCHAR(64) NOT NULL,
    trade_date DATE NOT NULL,
    signal_type VARCHAR(64) NOT NULL,
    signal_level VARCHAR(32),
    trend_state VARCHAR(32),
    close_price DECIMAL(20, 6),
    ma5 DECIMAL(20, 6),
    ma10 DECIMAL(20, 6),
    ma20 DECIMAL(20, 6),
    ma60 DECIMAL(20, 6),
    rsi14 DECIMAL(10, 4),
    atr14 DECIMAL(20, 6),
    volume_ratio DECIMAL(12, 4),
    technical_score INT,
    signal_reason TEXT,
    risk_note TEXT,
    ai_risk_score INT,
    ai_risk_level VARCHAR(32),
    final_action VARCHAR(64),
    position_policy VARCHAR(64),
    decision_reason TEXT,
    reject_reason TEXT,
    executed TINYINT DEFAULT 0,
    execution_date DATE,
    execution_price DECIMAL(20, 6),
    execution_note TEXT,
    follow_up_status VARCHAR(32) DEFAULT 'PENDING',
    follow_up_date DATE,
    follow_up_price DECIMAL(20, 6),
    follow_up_return_rate DECIMAL(12, 4),
    follow_up_note TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_trade_journal_signal (symbol_code, trade_date, signal_type),
    INDEX idx_trade_journal_symbol_date (symbol_code, trade_date),
    INDEX idx_trade_journal_signal_type (signal_type),
    INDEX idx_trade_journal_final_action (final_action),
    INDEX idx_trade_journal_executed (executed),
    INDEX idx_trade_journal_follow_up_status (follow_up_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS backtest_result_snapshot (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    symbol_code VARCHAR(64) NOT NULL,
    strategy_type VARCHAR(64),
    start_date DATE,
    end_date DATE,
    initial_capital DECIMAL(20, 6),
    position_ratio DECIMAL(12, 6),
    fee_rate DECIMAL(12, 6),
    slippage_rate DECIMAL(12, 6),
    lot_size INT,
    final_equity DECIMAL(20, 6),
    total_return_rate DECIMAL(12, 4),
    annualized_return_rate DECIMAL(12, 4),
    max_drawdown_rate DECIMAL(12, 4),
    win_rate DECIMAL(12, 4),
    trade_count INT,
    request_json LONGTEXT NOT NULL,
    result_json LONGTEXT NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_backtest_record_symbol_created (symbol_code, created_at),
    INDEX idx_backtest_record_strategy (strategy_type),
    INDEX idx_backtest_record_created (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
